apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-webapp-eventlistener
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-sample-webapp-listener
    weight: 100
