apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-webapp-pipelinerun
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: sample-webapp-pipeline
  resources:
    - name: docker-source-ppc
      resourceRef:
        name: git-source-ppc
    - name: docker-source-x86
      resourceRef:
        name: git-source-x86
    - name: test-cluster
      resourceRef:
        name: x86-cluster
    - name: builtImage-x86
      resourceRef:
        name: quay-resource-x86
    - name: builtImage-ppc
      resourceRef:
        name: quay-resource-ppc
