apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: quay-resource-ppc
spec:
  type: image
  params:
    - name: url
      value: quay.io/snehakpersistent/tekton-multi-arch:ppc64le
