apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: x86-cluster
spec:
  type: cluster
  params:
    - name: url
      value: https://c108-e.eu-gb.containers.cloud.ibm.com:31206
    - name: token
      value: sha256~E_k6THndDC9UpeZpvGzSO15AhzCTLZKsPf_tmy_hxRY
    - name: user
      value: IAM#sneha.kanekar1@ibm.com
    - name: insecure
      value: "true"
