apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-app
spec:
  resources:
    inputs:
      - name: docker-source-ppc
        type: git
      - name: builtImage-app
        type: image
      - name: test-cluster-ppc
        type: cluster
  steps:
    - name: deploy-app
      image: centos:latest
      env:
        - name: "KUBECONFIG"
          value: "/workspace/test-cluster-ppc/kubeconfig"
      script: |
        #!/bin/sh
        yum install -y wget tar git
        wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.6/linux-ppc64le/oc.tar.gz
        tar -xvf oc.tar.gz
        export PATH=$PATH:/
        export KUBECONFIG=$KUBECONFIG
        oc get nodes
        ocprojectcheck=0
        oc project sample-app-project || ocprojectcheck=$?
        echo $ocprojectcheck
        if [ $ocprojectcheck == 1 ];
        then 
        oc new-project sample-app-project ;
        oc new-app --name hello-world-app $(resources.inputs.builtImage-app.url) -n sample-app-project ;
        fi
        if [ $ocprojectcheck == 0 ]; then oc import-image hello-world-app:ppc64le -n sample-app-project ; fi
        if [ $ocprojectcheck == 1 ]; then 
        oc create route edge hello-world-app --service=hello-world-app --port=8080-tcp --insecure-policy=Redirect -n sample-app-project ;
        fi

