apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-arch-specific-image-x86
spec:
  resources:
    inputs:
      - name: docker-source
        type: git
      - name: test-cluster
        type: cluster
    outputs:
      - name: builtImage-x86
        type: image
  steps:
    - name: build-and-push
      image: centos:latest
      env:
        - name: "KUBECONFIG"
          value: "/workspace/test-cluster/kubeconfig"
        - name: "https_proxy"
          value: "http://sneha-3d3ceb-bastion-0:3128"
        - name: "http_proxy"
          value: "http://sneha-3d3ceb-bastion-0:3128"       
      script: |
        #!/bin/sh
        yum install -y wget tar
        wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.6/linux-ppc64le/oc.tar.gz
        tar -xvf oc.tar.gz
        export PATH=$PATH:/
        ls /workspace/
        oc get nodes
        rpm -Uvh https://github.com/tektoncd/cli/releases/download/v0.16.0/tektoncd-cli-0.16.0_Linux-ppc64le.rpm
        oc project tekton-pipelines
        oc apply -f $(resources.inputs.docker-source.path)/config/sa-pipeline.yaml
        oc apply -f $(resources.inputs.docker-source.path)/on-x86-cluster/git-resource-x86-oncluster.yaml
        oc apply -f $(resources.inputs.docker-source.path)/pipelineresources/quay-resource-x86.yaml
        oc apply -f $(resources.inputs.docker-source.path)/on-x86-cluster/task-x86-oncluster.yaml
        oc apply -f $(resources.inputs.docker-source.path)/on-x86-cluster/taskRun-x86-oncluster.yaml
        tkn taskrun logs --last -f
        
