apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: sample-webapp-triggertemplate
spec:
  params:
  - name: pathToDockerFile-app
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-ppc
    spec:
      type: git
      params:
        - name: revision
          value: main
        - name: url
          value: https://github.com/snehakpersistent/sample-web-app
        - name: httpsProxy
          value: "http://sneha-3d3ceb-bastion-0:3128"
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: ppc-cluster
    spec:
      type: cluster
      params:
        - name: url
          value: https://api.sneha-3d3ceb.130.198.103.117.nip.io:6443
        - name: user
          value: admin
        - name: token
          value: token
        - name: insecure
          value: "true"
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: quay-resource-app
    spec:
      type: image
      params:
        - name: url
          value: quay.io/snehakpersistent/tekton-sample-app:ppc64le
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: sample-webapp-pipelinerun
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: sample-webapp-pipeline
      params:
        - name: pathToDockerFile-app
          value: $(tt.params.pathToDockerFile-app)
      resources:
        - name: docker-source-ppc
          resourceRef:
            name: git-source-ppc
        - name: builtImage-app
          resourceRef:
            name: quay-resource-app
        - name: test-cluster-ppc
          resourceRef:
            name: ppc-cluster
