apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-webapp-pipeline
spec:
  params: 
    - name: pathToDockerFile-app
  resources:
    - name: docker-source-ppc
      type: git
    - name: builtImage-app
      type: image
    - name: test-cluster-ppc
      type: cluster
  tasks:
    - name: build-app-image
      taskRef:
        name: build-app-image
      resources:
        inputs:
          - name: docker-source-ppc
            resource: docker-source-ppc
        outputs:
          - name: builtImage-app
            resource: builtImage-app
    - name: deploy-app
      taskRef:
        name: task-deploy-app
      runAfter:
        - build-app-image
      resources:
        inputs:
          - name:  docker-source-ppc
            resource: docker-source-ppc
          - name: builtImage-app
            resource: builtImage-app
          - name: test-cluster-ppc
            resource: test-cluster-ppc
