apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-webapp-pipelinerun
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: sample-webapp-pipeline
  params:
    - name: pathToDockerFile-app
      value: app/Dockerfile
  resources:
    - name: docker-source-ppc
      resourceRef:
        name: git-source-ppc
    - name: builtImage-app
      resourceRef:
        name: quay-resource-app
    - name: test-cluster-ppc
      resourceRef:
        name: ppc-cluster
