apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source-ppc
spec:
  type: git
  params:
    - name: revision
      value: simple-pipeline
    - name: url
      value: https://github.com/snehakpersistent/sample-web-app
    - name: httpsProxy
      value: "http://address:port"
