apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source-x86
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/snehakpersistent/sample-web-app
    - name: httpsProxy
      value: "http://sneha-3d3ceb-bastion-0:3128"
