apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ppc-cluster
spec:
  type: cluster
  params:
    - name: url
      value: https://api.sneha-3d3ceb.130.198.103.117.nip.io:6443
    - name: user
      value: admin
    - name: token
      value: token
    - name: insecure
      value: "true"
