apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: ppc-cluster
spec:
  type: cluster
  params:
    - name: url
      value: <server_url>
    - name: user
      value: admin
    - name: token
      value: <token_value>
    - name: insecure
      value: "true"
