apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: quay-resource-multiarch
spec:
  type: image
  params:
    - name: url
      value: quay.io/snehakpersistent/tekton-multi-arch:latest
