apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-api-repo-webhook-run
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "github_username"
    - name: GitHubUser
      value: "github_username"
    - name: GitHubRepo
      value: "repository_name"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: <Eventlistener url>
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
